# Generated by Django 4.2 on 2023-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0002_file_alter_sentence_pdf_file_delete_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
